### announce the next applied micro seminar and circulate the sign up sheet

# load libraries 
library(gmailr)
library(googlesheets4)

# set directory to current folder
rootdir <- "C:/Users/yhwang18/Dropbox/Document/GitHub/SeminarOrganizer"
setwd(rootdir)

# first check if there is any seminar scheduled within the next 7 days
source("setGmailConfig.R")

if (daysleft[ind]<7 & daysleft[ind]>=1){
  
  # update the sign up sheet to a blank page
  range_clear(signup_link,range="B4:B13")
  range_clear(signup_link,range="A2:B2")
  
  signuphead=as.data.frame(cbind(paste0(speaker_name," sign up"),paste0("Date : ",seminar_date)))
  colnames(signuphead)=NULL
  range_write(signup_link,data=signuphead,range="A1")
  
  # compose a group email
  msg_heading <- paste0("Dear all, \n\n")
  
  ### feel free to modify the email text body, msg_body
  msg_body <- paste0(speaker_name," from ",speaker_institution, " will be our next seminar speaker.\n\n")
  
  if (!is.na(paper_title)){
    msg_body <- paste0(msg_body,"The speaker will present '", paper_title, "' on ", seminar_date," at ", seminar_time, ".\n\n")
  }
  
  if (!is.na(paper_link)){
    msg_body <- paste0(msg_body,"You can find the draft in the following link.\n",paper_link,"  \n\n")
  }
  
    msg_body <- paste0(msg_body,"Faculties can sign up for a one-to-one meeting slot in the following link.\n",signup_link,
                     "\n Graduate students can sign up after ",grad_signup_time,".\n\n")
  
  
  if (seminar_place=="virtual"){
    msg_body <- paste0(msg_body, "This is a virtual visit.\n",
                     "The zoom link for the seminar is\n",zoom_link,"\n\n",
                     "The zoom link to meet the speaker one-to-one is \n",meeting_link,"\n\n")
  } else{
    msg_body <- paste0(msg_body, "This is an in-person visit.\n",
                       "The one-to-one meetings will be in either speaker's office or each faculty's office.\n",
                       "The seminar room is W603.\n\n")
  }
  
  msg_end <- paste0("Best,\n",organizer_name)
  
  msg_note <- "\n\n----------\n\nNote : This email was automatically generated by a program. \nPlease excuse the brevity and any errors. Thanks.\n"
  
  msg <- paste0(msg_heading,msg_body,msg_end,msg_note)
  
  ### set a correct receiver email address inside gm_to()
  emailmsg <- gm_mime() %>%
    gm_to(paste0(audience_email,",",organizer_email)) %>%
    gm_from(organizer_email) %>%
    gm_subject(paste0("Next Applied Micro Seminar Sign-Up (",speaker_name,")")) %>%
    gm_text_body(msg)
  
  ### send an email
  gm_send_message(emailmsg)
  
  
  
}