#### remind the applied micro seminar in the afternoon
# load libraries again
library(gmailr)
library(googlesheets4)

# set directory to current folder
rootdir <- "C:/Users/yhwang18/Dropbox/Document/GitHub/SeminarOrganizer"
setwd(rootdir)

# first check if there is any seminar scheduled today
source("setGmailConfig.R")

if (daysleft[ind]==0){

  msg_heading <- paste0("Dear all, \n\n")
  
  ### feel free to modify the email text body, msg_body
  msg_body <- paste0("This is a reminder that we have an applied micro seminar tomorrow afternoon (",seminar_date,") at ", seminar_time,".\n\n")
  
  if (seminar_place=="virtual"){
    msg_body <- paste0(msg_body,"The seminar and the one-to-one meetings will be done virtually.\n",
    "The zoom link for the seminar is \n",zoom_link,
    "\n\n The zoom link to meet the speaker one-to-one is \n",meeting_link,
    "\n\n You can see the one-to-one meeting schedule at \n",signup_link,
    "\n\n See you all soon!\n\n")
  } else{
    msg_body <- paste0(msg_body,"This is an in-person seminar.\n",
                       "The seminar room is W603.",
                       "\n\n You can see the one-to-one meeting schedule at \n",signup_link,
                       "See you all soon!\n\n")
    
  }
  
  msg_end <- paste0("Best,\n",organizer_name)
  
  msg_note <- "----------\n\nNote : This email was automatically generated by a program. \nPlease excuse the brevity and any errors. Thanks.\n"
  
  msg <- paste0(msg_heading,msg_body,msg_end,msg_note)
  
  ### set a correct receiver email address inside gm_to()
  emailmsg <- gm_mime() %>%
    gm_to(paste0(audience_email,",",speaker_email,",",organizer_email)) %>%
    gm_from(organizer_email) %>%
    gm_subject(paste0("Reminder : Today's applied micro seminar (",speaker_name,")")) %>%
    gm_text_body(msg)
  
  ### send an email
  gm_send_message(emailmsg)
  
}

